services:
  backend:
    build:
      context: .
      dockerfile: backend/DockerFile
    container_name: virtual-library-backend
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app

  frontend:
    build:
      context: .
      dockerfile: frontend/DockerFile
    container_name: virtual-library-frontend
    ports:
      - "5173:5173"
    env_file:
      - ./frontend/.env
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend